env_id: "roundabout-v0"
render_mode: null

env_params:
  observation:
    type: "Kinematics"
    vehicles_count: 25
    
    features: ["presence", "x", "y", "vx", "vy", "cos_h", "sin_h"]
    features_range:
      x: [-100, 100]
      y: [-100, 100]
      vx: [-20, 20]
      vy: [-20, 20]

    absolute: False
    order: sorted

  action:
    type: "DiscreteMetaAction"

  simulation_frequency: 15
  policy_frequency: 1
  duration: 20
  
  # Ödül Ayarları (Dengeli / Balanced)
  collision_reward: -2.0
  lane_change_reward: -0.05
  right_lane_reward: 0.1
  high_speed_reward: 0.2

agent_params:
  algorithm: "PPO"
  total_timesteps: 100000   
  save_path: "models/roundabout_ppo_best_model"
  tensorboard_log: "logs/tensorboard/"
  checkpoint_freq: 50000
  
  model_params:
    learning_rate: 0.0003
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
    gamma: 0.95
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.01
    verbose: 1
    
    policy_kwargs:
      net_arch: [256, 256]